//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuevaPracticaSomee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dias_semana
    {
        public int id_dia { get; set; }
        public string dia { get; set; }
        public Nullable<int> id_home { get; set; }
        public Nullable<int> id_grupo { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual home home { get; set; }
    }
}
