//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuevaPracticaSomee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int dni_empleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_de_nacimiento { get; set; }
        public string sexo { get; set; }
        public Nullable<int> id_sector { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public string password { get; set; }
        public Nullable<int> piso { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual piso piso1 { get; set; }
        public virtual sector sector { get; set; }
        public virtual home home { get; set; }
    }
}
